### PR TITLE
BREAKING CHANGE: added default region and locale values to all API

### PR DESCRIPTION
**Pull request by Iru**
## Pull Requests
This request addresses #51.

Core changes:
1. `region` and `locale` are now named-only parameters with defaults of `None` and typing based on the `Region` and `Locale` enumerators.
2. `ApiEndpoint` class added to track the core API attributes (`client_id`, `client_secret`, `region`, & `locale`) separately from the API methods.  The class has `extend_endpoint()` method  of this class to support composability.
3. `BaseApi` and all endpoint classes, e.g., `Diablo3Api`, now inherit from `ApiEndpoint`.  `BaseApi` has a helper method to handle default and invalid `region` vales.
4. `LocaleApi` class added that extends `BaseApi` to handle default locale logic.  `LocaleApi` has a helper method to handle default and invalid `locale` values
5. API service classes, e.g., `WowProfileApi`, now inherit from `LocaleApi` instead of `BaseApi` where appropriate, i.e., they access resources that are `locale` aware.
6. tests added for different permutations of default, overridden, and invalid `region` and `locale` values.  Existing tests edited to function correctly under new method signatures, i.e. parameters named and sequenced appropriately.

This PR also includestwo items slightly outside the original scope of #51:
1. Adding the `ApiEndpoint` class let me simplify the different endpoint classes, e.g., `Diablo3Api`.  They now only include `extend_endpoint()` method that creates the needed API access points, e.g., `.game_data`, which is then invoked by `ApiElement.__init__()`
2. I also simplified `WowProfileApi` and `WowGameDataApi` classes by collapsing the namespace and is_classic logic into a set of 'private' methods.  I can strip that into a separate PR if you'd prefer.

### CODE REVIEW

**Comment by lostcol0ny** [comment]
A few things to fix before I can merge:

1. `blizzardapi2/api.py:5` has `from unittest.mock import Base`. Looks like an IDE auto-import accident. Pulls a test-time dep into the production import graph. Remove it.
2. `poetry.lock` got committed and `[dependency-groups]` is written in Poetry's parenthesized version syntax. This repo is uv-only (CI uses uv). Drop the lockfile and convert specifiers to PEP 508.
3. `Diablo3CommunityApi` got skipped in the keyword-only migration. Its endpoints still take `region`/`locale` positionally and the docstrings still describe the old signature. Every other game API has `*,` now.
4. While you're in there: `LocaleApi.get_resource` overwrites a caller-supplied `locale` in `query_params` because of the dict-merge order at `api.py:238`. And the `LocaleApi` class docstring still has the IDE template stub (`Args: BaseApi (_type_): _description_`).

Also, let's take the offer to split the WoW `_get_static_resource`/`_get_dynamic_resource` refactor into a follow-up PR. The default-region/locale change is what makes this v4. The WoW helper refactor is its own thing and dominates the diff. I'll merge the follow-up right after this lands.

Test suite is green, token-pop contract is preserved with explicit tests, 401 retry and CN routing intact. Get those four items in and we're set.

**Comment by Iru** [comment]
Main branch updates merged in and PR updated addressing all points.

That includes the change allowing the passing of a locale to `get_resource()` via query_params.  If passed that way, the code **does not** attempt to validate the result. I also added.a test for that stiuation.

**Comment by lostcol0ny** [comment]
### Code review

Found 3 issues:

1. `from typing import Optional, TypeAliasType` breaks Python 3.11 — `TypeAliasType` was added to `typing` in 3.12 (the project's CLAUDE.md says "Python 3.11+ only"). The symbol is also unused — `OptionalRegion`/`OptionalLocale` are plain `Optional[...]` assignments that don't need a runtime alias object. This is the cause of the failing `test (3.11)` CI job (`ImportError: cannot import name 'TypeAliasType' from 'typing'`).

Fix:

```diff
-from typing import Optional, TypeAliasType
+from typing import Optional
```

If PEP 695-style aliases are desired later, `typing_extensions.TypeAliasType` works on 3.11+ — but plain assignment is fine here.

https://github.com/lostcol0ny/blizzardapi2/blob/83682d80ce0373b9296d4eb54b4cb9cba8eb67f2/blizzardapi2/types.py#L1-L4

2. `BattlenetOAuthApi.get_user_info` reorders positional args without a `*,` shim — old signature was `get_user_info(self, region, access_token)`; new is `get_user_info(self, access_token, region=None)`. Any existing caller using positional args (`oauth.get_user_info("us", token)`) will silently bind the region string as `access_token` and the token as `region`, leading to a 401 with `Authorization: Bearer us` or a `ValueError` from `Region(token)`. CLAUDE.md says "every name, parameter shape, and return type is part of the contract for external users." Either restore the original positional order or make `region` keyword-only with `*,`.

https://github.com/lostcol0ny/blizzardapi2/blob/83682d80ce0373b9296d4eb54b4cb9cba8eb67f2/blizzardapi2/battlenet/battlenet_oauth_api.py#L24-L28

3. `LocaleApi.get_resource` is an LSP-incompatible override of `BaseApi.get_resource` — position 4 changes meaning from `query_params` (parent) to `locale` (child). Pyright flags this as `reportIncompatibleMethodOverride`. Anyone holding a `BaseApi` reference and calling `instance.get_resource(resource, region, my_query_params)` positionally will, at runtime on a `LocaleApi`, bind their dict to `locale`, then `Locale({...})` raises `ValueError`. Make `locale` keyword-only (`*, locale=None`) so the parent's positional contract is preserved, or move it to the end after `query_params`.

https://github.com/lostcol0ny/blizzardapi2/blob/83682d80ce0373b9296d4eb54b4cb9cba8eb67f2/blizzardapi2/api.py#L207-L220

**Comment by Iru** [comment]
1. Fixed.  Stupid over-helpful IDE.  I've changed to a 3.11 environment for this package instead of my default version of python (3.14) to avoid future failures
2. Fixed.  Stupid coder not grepping files.
3. See my comments below.  I'd like your reaction before committing anything

I see two other alternatives to adding a no-op parameter to `BaseAPI.get_resource()`

1. Have region` and `locale` be named-only parameters in BaseApi & LocaleApi (query_params would also be named-only as a consequence)
  - Pros: makes these methods consistent with the rest of the package
  - Cons: adds to the diff significantly because all the `super().get_resource(resource, region, locale, ...)` calls have to change to `super().get_resource(resource, region=region, region=locale, ...)`.  That's 269 changes in total.
2. Change `query_params` to `**query_params` in `BaseAPI.get_resource()` and `LocaleAPI.get_resource()`
  - Pros: makes the interface more pythonic.  `**kwargs` is build for passing varidict arguments.  Having to explicitly pass a dict feels hackish IMHO, even though I realise it's how `requests` does it.
  - Cons: adds to the diff significantly because all `super().get_resource(resource, ..., query_params)` have to change to `super().get_resource(resource, ..., **query_params)`.  That's 203 changes in total.  However most of those changes are in the `WowProfileApi` and `WowGameDataApi`, and could be handled by the withdrawn refactoring changes.

I've already committed the first two changes (and installed `pyright` for future checking).  Let me know your preferred path for the signature change and I'll finish that tonight

**Comment by lostcol0ny** [comment]
### Code review

Found 1 issue:

1. `LocaleApi.get_resource` is still an LSP-incompatible override of `BaseApi.get_resource` — `locale` sits at position 4 where the parent has `query_params`. Pyright flags this as `reportIncompatibleMethodOverride`. The contributor proposed two design alternatives in [#issuecomment-4390325341](https://github.com/lostcol0ny/blizzardapi2/pull/55#issuecomment-4390325341) and is waiting on your call before fixing.

https://github.com/lostcol0ny/blizzardapi2/blob/e67c2f95b1b270aee5dea839119d5c2fd2113eb2/blizzardapi2/api.py#L207-L220

Previous issues #1 (`TypeAliasType` import) and #2 (`get_user_info` positional reorder) are cleanly addressed at this head.

A few minor items showed up below the surfacing threshold, worth tracking but not blockers:

- `Diablo3GameDataApi.get_era_index` still lacks the `*,` keyword-only marker that every other method in the file has — one-line follow-up: https://github.com/lostcol0ny/blizzardapi2/blob/e67c2f95b1b270aee5dea839119d5c2fd2113eb2/blizzardapi2/diablo3/diablo3_game_data_api.py#L62-L65
- `[dependency-groups]` removal in `pyproject.toml` dropped `isort` from declared dev deps. Not currently wired into CI or pre-commit, but worth confirming intent.
- `BattlenetOAuthApi.get_user_info` docstring lists `region` before `access_token` in `Args:`, but the signature has `access_token` first: https://github.com/lostcol0ny/blizzardapi2/blob/e67c2f95b1b270aee5dea839119d5c2fd2113eb2/blizzardapi2/battlenet/battlenet_oauth_api.py#L25-L42

**Comment by lostcol0ny** [comment]
Going with option A — keyword-only across both classes.

The issue with B: `**query_params` doesn't actually fix the LSP problem, it shifts it from static to runtime. Consider this call:

```python
obj.get_resource("/data/wow/realm/index", region="us", locale="en_US")
```

On `BaseApi` (with `**query_params`), `locale="en_US"` gets absorbed into the kwargs dict and goes out as a URL query param. On `LocaleApi`, it's consumed by the explicit `locale` parameter, validated through `Locale(...)`, then re-inserted into the params dict. Same call, different semantics depending on the runtime type. Pyright won't catch that — both signatures are statically valid.

A keeps the contract explicit and consistent. The ~269 changes are mostly a regex pass on `super().get_resource(...)` callsites — one-time mechanical cost.

If the diff feels heavy, fine to stage it: signature change on `BaseApi`/`LocaleApi` first, then internal callers in a follow-up commit on the same PR. Or land it all together if it's quicker. Either way.

**Comment by Iru** [comment]
Option A committed along with a completed transition to Region & Locale everywhere, including doc strings.
I also put `isort` back in the dev dependencies and added `poetry.lock` to `.gitignore`, so it doesn't accidentally included again in the future.

All tests pass under 3.11

I'll do the wow api refactoring as a second PR.  This one has been messy enough

**Comment by lostcol0ny** [comment]
@Iru — to break the back-and-forth, I pushed a set of fixes directly to your branch. The architectural direction here (`ApiEndpoint`, `LocaleApi`, default region/locale plumbing) is the right call and I want it to land. Walking through what I changed:

**`chore: drop committed dev artifacts and gitignore *.patch`**

The 4 `.patch` files looked like git-diff snapshots saved during your local refactor — removed them and added `*.patch` to `.gitignore`. Also dropped `example.ipynb`: the embedded JSON outputs put it at ~5 MB and 124k lines, and it references an undefined `_api_client3` (the line `_api_client3 = Blizzard` looks truncated mid-edit), so it can't run end-to-end as-is. If you want a runnable example to ship with the package, a plain `examples/quickstart.py` in a follow-up PR would be easier to review and won't churn diffs.

**`fix(api): drop ignored locale param from BaseApi, copy query_params`**

Two issues:

- `BaseApi.get_resource` accepted a `locale` kwarg that the body never read — a silent trap for anyone subclassing `BaseApi` for a non-locale endpoint. I dropped the parameter and let the two `get_resource` signatures diverge to reflect the actual `BaseApi` vs `LocaleApi` split. To preserve LSP, `locale` is now keyword-only on `LocaleApi.get_resource` with `query_params` in the `BaseApi`-aligned position 3. ~218 internal `super().get_resource(...)` callsites updated to pass `locale=locale`.
- `LocaleApi.get_resource` was mutating the caller's `query_params` dict (missing the `.copy()` that `_make_request` already had). Two calls sharing a dict would accumulate the locale. Fixed.

**`fix(wow): wire up namespace helpers across all game-data methods`**

The headline one. `_get_static_resource` / `_get_dynamic_resource` were defined but never called — every leaf method still inlined `f"static-{region}"`. With the new default-region feature, calling any `wow.game_data` method without an explicit region produced `namespace="static-None"`, which Blizzard rejects. Swept all 147 leaf methods to call the helpers:

- 88 plain static, 17 plain dynamic
- 29 + 7 `is_classic` toggles
- 2 hardcoded `dynamic-classic` (CLASSIC ONLY methods)
- 4 search methods passing `**query_params`

`wow_game_data_api.py` shrinks by ~485 lines as a side effect — the helpers paid off, they just hadn't been wired up yet.

**`test(wow): regression guard for default-region namespace resolution`**

5 tests that instantiate `WowApi` with constructor-supplied defaults, call leaf methods *without* passing region/locale, and assert `"None"` never reaches the namespace string. The existing tests always passed region explicitly so they wouldn't have caught the original bug.

If anything here conflicts with your intent or you'd rather have handled something differently, push back before I merge.

**Comment by Iru** [comment]
I'm fine will all the above.  Getting default values for region & locale in place was my sole goal.  How that happens is less important. 

My apologies for all the extra work I've created.  Some of this is poor tools use/management on my part, e.g., the patch files should never have been committed, IDE inserted modules.  Some is me rushing and not checking my work better, e.g., leaving the helpers in wow.game_data but then not using them.

**Comment by lostcol0ny** [comment]
Never a problem! I'm not even a real dev so I'm in no position to judge at all.
